### ISSUE TITLE
Redaction of names

### ISSUE THREAD

**Issue by gauravyemula** [cegme/cis6930fa24project1-data#100]
In arpitapatnaik-names-in
![Screenshot 2024-10-31 at 12 04 57 AM](https://github.com/user-attachments/assets/ada5c3c6-9419-4f15-bd85-15d70969c02c)

Here there's a line with =G and in this example they are considering it as name. I don't think G is a name.

**Comment by cegme** [comment]
Interesting point. I agree in general. But as a signature it is serving as a name. I'll keep it.
Close
