### ISSUE TITLE
Referring to yichengwang-concept-star-out

### ISSUE THREAD

**Issue by gadhaunaslam** [cegme/cis6930fa24project1-data#101]
In the output file (yichengwang-concept-star-out):

Concept: STAR 

The initial email information is censored which should not be:
Enron Houston@ENRON>
X-cc: 
X-bcc: 
X-Folder: \Neal, Scott\Neal, Scott\Inbox
X-Origin: NEAL-S
X-FileName: Neal, Scott.pst

The names, dates and timings are also censored, but the sentence that should be censored would be the first line for each block below (at least to my understanding):

Star Wars: Episode IV-A New Hope
Directed by George Lucas
(USA, 1977, 125 min.)
Friday, May 4, 7:30 p.m.
Saturday, May 5, 11:00 a.m.

Star Wars: Episode V-The Empire Strikes Back
Directed by Irvin Kershner
(USA, 1980, 120 min.)
Friday, May 11, 7:30 p.m.
Saturday, May 12, 11:00 a.m.

Star Wars: Episode VI-Return of the Jedi
Directed by Richard Marquand
(USA, 1983, 132 min.)
Friday, May 18, 7:30 p.m.
Saturday, May 19, 11:00 a.m.

Star Wars: Episode I-The Phantom Menace
Directed by George Lucas
(USA, 1999, 133 min.)
Friday, May 25, 7:30 p.m.
Saturday, May 26, 11:00 a.m.

Lastly, considering that the following lines are censored:
"It's a Girl" performed by Weave Dance Company 
Weave Dance Co. will perform May 24-26 at 8:00 p.m. at Stages Repertory Theater, 3201 Allen Parkway at Waugh, Call 713-52STAGE for tickets.  This performance, called "It's a Girl!" celebrates pregnancy and motherhood. 

Donations to the Houston Area Women's Center will be collected at the performance.  

The below line should also be censored too, which is not:
Matinee admission (show times before 5:00 p.m.) is $4

**Comment by cegme** [comment]
I disagree about what needs to be redacted. The redacton locations do seem to be incorrect we will not use this
