### ISSUE TITLE
Concept Redaction

### ISSUE THREAD

**Issue by Surya-teja-18315** [cegme/cis6930fa24project1-data#94]
https://github.com/cegme/cis6930fa24project1-data/blob/51c03dba1640f91c517260bc42cc4adea6fbcc8e/arpitapatnaik-concept-wine-in#L2C4-L10C35

![image](https://github.com/user-attachments/assets/e1eec0d2-ac19-4a98-98cc-b852201e103d)

Given Output:
![image](https://github.com/user-attachments/assets/70cafc19-3c18-4f29-baba-8956d9d5ab6b)

The given concept is summer for this test case , for the output as there is no full stop , but there is full stop only at the end of the address. Upto Where we need to stop redacting?

![image](https://github.com/user-attachments/assets/ca5fa548-a083-44a2-b2bb-4bdfd56d3919)
Redacted until the sentence ended, is this correct?

**Comment by cegme** [comment]
This is a good point. This depends on the end of a sentence. Multiple colons an capitalization could indicate that a sentence has ended.

**Comment by cegme** [comment]
Controversial but I am keeping it.
