### ISSUE TITLE
Name Redaction

### ISSUE THREAD

**Issue by poseidon-tech** [cegme/cis6930fa24project1-data#97]
### Issue Description
[https://github.com/cegme/cis6930fa24project1-data/blob/main/is.arora-names-out](https://github.com/cegme/cis6930fa24project1-data/blob/main/is.arora-names-out)
The output file appears to be incorrect. Specifically, at [line 9 of this file](https://github.com/cegme/cis6930fa24project1-data/blob/main/is.arora-names-out), the `X-To` header, which should be on line 10, is mistakenly placed on line 9 and is getting redacted.

**Given Input:**

![image](https://github.com/user-attachments/assets/e5d6c28e-4571-4f7d-b17e-61190c2e8352)

**Given Output:**

![image](https://github.com/user-attachments/assets/5fdea995-c5ad-49cf-9833-2503057bb808)

**Expected Output:**

![image](https://github.com/user-attachments/assets/3ad0d786-b8a4-4d20-8faa-e4e8e873ed0b)

**Comment by cegme** [comment]
Agreed. Updated.
